global:
  marketplace-ami: false
  owner: quickstart-eng@amazon.com
  qsname: quickstart-github-enterprise
  regions:
    - ap-northeast-1
    - ap-northeast-2
    - ap-south-1
    - ap-southeast-1
    - ap-southeast-2
    - eu-central-1
    - eu-west-1
    - sa-east-1
    - us-east-1
    - us-west-1
    - us-west-2
  reporting: true
 
tests:
  quickstart-github-enterpriset1:
    parameter_input: quickstart-github-enterprise-example-params1.json
    template_file: quickstart-github-enterprise-example1.template
  quickstart-github-enterpriset2:
    parameter_input: quickstart-github-enterprise-example-params2.json
    template_file: quickstart-github-enterprise-example2.template
